import Head from 'next/head'
import TypeWriterEffect from 'react-typewriter-effect';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import {useDispatch, useSelector} from 'react-redux'
import {globaluse} from '../context/global'
import HomeCard from '../components/cards/homecard'
export default function Home() {
  const {name,products} = useSelector((state) => state.global)
  const {userinfo} = globaluse()
  const myRef = document.querySelector('.scrollable-div')



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>

<TypeWriterEffect
className='mt-12 ml-12'
            textStyle={{ fontFamily: 'Red Hat Display' ,fontSize: '2rem',marginTop: '2rem'}}
            startDelay={100}
            cursorColor="black"
            text="This is a single text"
            typeSpeed={100}
            scrollArea={myRef}
          />




</div>
   
    </div>
  )
}
