import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import {useDispatch, useSelector} from 'react-redux'
import {globaluse} from '../context/global'

export default function Home() {
  const {name,products} = useSelector((state) => state.global)
  const {userinfo} = globaluse()


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>
  hello {userinfo?.name}
<div>
 wsaw {products?.length}
</div>




</div>
   
    </div>
  )
}
