import Head from 'next/head'
import dynamic from 'next/dynamic'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState,useRef } from 'react'
import {useDispatch, useSelector} from 'react-redux'
import {globaluse} from '../context/global'
import Paginate from '../components/parac/paginate'
import HomeCard from '../components/cards/homecard'
import Latestproducts from '../components/home/latestproducts'

const  Typewriter = dynamic(() => import('../components/typewriter'), {
  ssr: false
})


export default function Home() {
  const {name,products} = useSelector((state) => state.global)
  const {userinfo} = globaluse()



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div>


<Typewriter />

<div>
<div className=' grid grid-cols-4 gap-4'>


{/* <Latestproducts /> */}





{/* {products.map((product) => (
<div>

  <HomeCard product={product}/>


</div>))} */}

<Paginate />

</div>



</div>




</div>
   
    </div>
  )
}
